### ISSUE TITLE
Changing value in Table Editor changes structure of whole file

### ISSUE THREAD

**Issue by WellBloud** [SeeSharpSoft/intellij-csv-validator#110]
I've set semicolon as value separator in *Editor > Code Style > CSV* and have only set *Enabled* to true on  *Tabularize* section. 
When changing a value (or simply clicking into a table cell) in *Table Editor* view, the whole file get reformatted - all lines have colons instead of semicolons, and double quote escaping is also removed on some fields.
Furthermore an empty line is inserted to the end of the file

Example:
```
1;"two";"three is longer"
4;"five ";"six is longer"
7;" eight";"nine is also longer"

```
becomes
```
1;two;three is longer
4;"five ";six is longer
7;" eight";nine is also longer
;;
```

**Comment by SeeSharpSoft** [comment]
> I've set semicolon as value separator in Editor > Code Style > CSV and have only set Enabled to true on Tabularize section.

The code style is meant for the text representation and is used when formatting the "code". The *value separator* doesn't really belong here anymore (it is in since before the table editor did exist) - I will move the setting as soon as I have found a proper solution for file based value-separator settings.

Keep in mind: All (other) settings you change here do not influence the table editor or how CSV is generated by the table editor.

> When changing a value (or simply clicking into a table cell) in Table Editor view, the whole file get reformatted

When a change is suspected/detected, the **content of the table is serialized** to CSV. When using the table editor, all operations are performed on a table like data-structure, not on the text representation.

>  all lines have colons instead of semicolons

This would actually be a bug, but your example doesn't show this behavior - and I cannot reproduce this neither. So do you really end up with colon separated values instead of semicolon separated values?

> double quote escaping is also removed on some fields.

There are two modes of serializing the table content to CSV: Either [quote all values](https://github.com/SeeSharpSoft/intellij-csv-validator#enforce-value-quoting) or only those that are required to quote (based on [RFC 4180](https://tools.ietf.org/html/rfc4180)).

> Furthermore an empty line is inserted to the end of the file

You already have an empty line in your original example, which is converted into an empty row with 3 cells in the table editor and due to serialization it is represented as `;;` in your case. If you delete the last line then it is gone for good. Note: I am thinking about a setting to support enforcing a linebreak at the end during table-to-CSV serialization as this seems to be a common code-style "issue".


**Summary:** Using the table editor is indeed overriding the text representation with the serialized table-data in CSV format. It will always generate valid CSV (assuming it is bug-free 😄) but there is no additional semantic layer in the CSV format (or the plugin) for e.g. quoting only "Strings" or adding/removing/ignoring empty lines or having comments etc. If you need your CSV in certain format following your required semantic you have to stick to the text-editor.

Does this cleared some things up for you?

**Comment by WellBloud** [comment]
I get that serializing whole table to CSV may be convenient, but in my case when you add/edit a single line and end up with the whole file changed (which is also shown in GIT, code reviews etc.) this is not good behavior. 
Optimal would be to set content serialization (all/required values) beforehand and a scope (whole file/modified lines etc.)

I'll stick with the text-editor for now and everything should be OK.
Thanks for clarification
