### ISSUE TITLE
Support comments for Color scheme

### ISSUE THREAD

**Issue by kecsap** [SeeSharpSoft/intellij-csv-validator#119]
It would be really nice if the plugin would support the comments in syntax highlighting (Color scheme). Usually, the csv parsers consider hash mark "#" as start of a comment line. I hope it is easy to add.

**Comment by SeeSharpSoft** [comment]
Thanks for the suggestion.

Comments are not part of [RFC 4180](https://www.ietf.org/rfc/rfc4180.txt), which is the leading standard that this [CSV Plugin](https://github.com/SeeSharpSoft/intellij-csv-validator#syntax-parser--validation) is based on. IMO the parsing and syntax validation should stay clean and strict, adding comments - even just supporting the highlighting - will lead to a "dirty" CSV format.

Just some examples (consider the following lines part of a CSV file):

```
# this is not "valid" CSV cause of the "
"# this would be ""valid"" but is probably not wanted"
# this is valid CSV, but the , would still be interpreted as a value separator
# prohibiting double quotes and commas in comments would work - but would it?
```

This are just some examples when thinking about the text editor and highlighting - the table editor is a whole other topic on top of it. How are comments supposed to be handled there?

**Comment by kecsap** [comment]
Although it is not in this standard, parsing libraries tend to implement comments for csv reading. E.g. Pandas in python:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

I personally don't want the hash mark handling to complicate your parsing. If it is easy to add a simple dumb rule to consider everything to a comment after a hash mark for syntax highlight, it is fine. If it is hard to add you can just close this issue, I understand your arguments.

**Comment by SeeSharpSoft** [comment]
I will leave it open for now - maybe there are some good ideas how to handle this. As of now, I don't see a proper solution especially for the table editor.

It is not the technical but the semantic aspects that concerns me. Parsing CSV (once) with adjustable settings is a different scope than providing an editor with a defined language, syntax validation, non-text editor etc.

I'd rather promote a clean CSV syntax (e.g. #9, #53 or [here](https://youtrack.jetbrains.net/issue/DBE-7217)) than trying to support all kinds of custom semantics and derivatives. Said this, I am using comments in my CSV files as well but value based with `/* just a comment */`... 😀

**Comment by Egwor** [comment]
It would be very helpful if this plugin did handle the comments! 

I think that there are two challenges:

1.  Formatting of code. If the auto-formatted ignored commented lines this would be a big win. This would avoid the scenario where the first column is made very wide. This is particularly annoying if you use the 'Auto-format' option in commits (because you then need to revert the auto-format). This would be a win in itself.

2. Handling the table editing. I think that there are a few options.
- Ignore the line entirely and the data is lost when save. Probably not ideal!
- Don't allow editing of CSV files in the table editor if there are comments
- Allow existence of the comment line as a row by creating a fake row (grey it out?) with no data in the other columns so that the table editor could work on it. If you artificially create a commented column at the start/end which is for contents of the comment then it could still be editable. 
- Link the comment with the line below it (or above it, if the line after is blank?). Ignore this in the table editor and then when save, restore the comment associated with the CSV row. This seems trickier to do to me?


I did start having a look at the code to see if I could add the handling of the comment on a specific branch so that I could get at least 1. but I'm not familiar enough with the IntelliJ lexing. I think I should be able to define the # as a comment. So something very very roughly like this (note the end of line comment should just be a comment, but that's not a massive concern right now):
```
(CsvLexer.flex)
END_OF_LINE_COMMENT=("#")[^\r\n]*
...
<YYINITIAL> {END_OF_LINE_COMMENT}                           { yybegin(YYINITIAL); return CsvTypes.COMMENT; }
```
and then some override in CsvParserDefintion for `getCommentTokens()`

If you have any pointers on how that could work, I can try having an explore.

**Comment by Egwor** [comment]
Is there a way to sponsor this change?

**Comment by SeeSharpSoft** [comment]
As I notice some kind of demand here 😉, I will have a look how to implement it - especially with respect to the Table Editor. Guess for the first iteration, the Table Editor will not be usable if a CSV file contains comments.
