### ISSUE TITLE
cant commentout csv lines with intelij keyboard shortcut

### ISSUE THREAD

**Issue by bbarski** [SeeSharpSoft/intellij-csv-validator#144]
cant commentout csv lines with intelij keyboard shortcut

**Comment by SeeSharpSoft** [comment]
CSV does not know about comments - see also #119

**Comment by bbarski** [comment]
> CSV does not know about comments - see also #119

some kind of solution is to give new line character after every record in csv and then delimiter/separator at beginning of line which you like to comment out.
it will pass null to a function
work for me
let me know what u think about it
greetings

**Comment by SeeSharpSoft** [comment]
> some kind of solution is to give new line character after every record in csv

There is no new line character in csv?!

I don't understand your solution - and I also don't understand, what this solution is for. Parsing and validation is not an issue.

The issue is a proper standardization of comments in CSV - it simply doesn't exist. And everyone uses comments in CSV in a slightly different way. Last but not least: How to handle any kind of comments in the table editor properly?

**Comment by SeeSharpSoft** [comment]
Lets keep #119 open for further concept ideas on comment handling in CSV...
