### ISSUE TITLE
Adding custom separator

### ISSUE THREAD

**Issue by patrickjusseau** [SeeSharpSoft/intellij-csv-validator#177]
Hello,

For our project we use '~§' as a custom separator. Any chance those 2 characters could be added as a custom separator to the plugin ?

Thanks in advance

**Comment by SeeSharpSoft** [comment]
@patrickjusseau Thanks for your request.

Unfortunately, this separator seems very specific to me. Supporting custom separators is [no piece of cake (see FAQ)](https://github.com/SeeSharpSoft/intellij-csv-validator#faq), and besides all of that, each new supported separator decreases the overall performance of the parser/lexer. Therefore, I'd like to focus on widely spread and often used separators.

Said this, I am willing to look into any contribution regarding custom separators, the performance on large CSV files must be convincing though.

**Comment by jusseau-p** [comment]
Thanks @SeeSharpSoft that makes perfectly good sense. Thanks anyway for this great plugin !

**Comment by gitandy** [comment]
Hi,
such a nice plugin. At least a custom single character separator would be nice, but I understand the circumstances. 
I've to open copies of /etc/passwd, /etc/group and need a colon as separator. So it would be nice to use a colon as separator.
Commonly used separators are ,;: TAB, SPACE and PIPE. Colon and Space would be a nice addition.
@patrickjusseau : with such a special separator I would look for a way to turn them to standard format. The semicolon is well understood in Excel and LibreOffice and very save due to it's rare use for anything else. So you get portability for your data and reduce the overhead (half of bytes for separators).

**Comment by SeeSharpSoft** [comment]
A first PoC showed a notable worse performance of my custom lexer (an unoptimized and simple implementation though) in comparison to the pre-compiled FlexLexer implementation, so flexibility comes with a price - to probably nobodys surprise.

Nevertheless, I decided to give the custom separator a GO with a custom lexer, which will only be used in case of a custom separator.

Furthermore, I will add the colon (:) to the list of default separators to leverage the better performance.

**Comment by jusseau-p** [comment]
That's great news, can't wait to try it out.

**Comment by SeeSharpSoft** [comment]
**Feature released with version CSV Plugin 2.11.0:**

Use the editor context menu entry *CSV Separator value > Custom* to define an arbitrary separator.

**Please note:** Just a *SPACE* is not supported as separator due to contradicting formatting options, e.g. trimming/adding spaces around separator, and tabularization.

**Comment by SeeSharpSoft** [comment]
After a troubling start with version 2.11.0 🙈, this feature is now available with the latest version - hence closing this issue.
