### ISSUE TITLE
PyCharm 2020.1 no CSV editor

### ISSUE THREAD

**Issue by ultiweb** [SeeSharpSoft/intellij-csv-validator#194]
I've installed 2.9.3 from the marketplace on the most current version of PyCharm and when I open a CSV file it opens as text. I've had your plugin installed on IntelliJ 2019.1 and it worked fine. If you need logging information or anything else I can do to help please let me know. I saw your -192 version for 2019.2, is it possible this is the same bug and it has crept back into the 2020.* Jetbrains IDE's?

**Comment by ultiweb** [comment]
My bad, I must be blind. I missed the configuration button. I must have used another CSV plugin in the past.

**Comment by SeeSharpSoft** [comment]
There is actually an issue with v2020.* that having the database plugin installed - the associated filetypes are overridden. #196 ensures that the plugins file types are used. "Edit as table..." can still be activated via context-menu.

Unfortunately, an [attempt for a better integration between this and the datagrid/database plugin](https://youtrack.jetbrains.com/issue/DBE-1845) some time ago turned out fruitless.
