### ISSUE TITLE
Sorting columns in version 2.10.0

### ISSUE THREAD

**Issue by andt88** [SeeSharpSoft/intellij-csv-validator#199]
Before the update to version 2.10.0 it was possible to sort columns. This seems no longer to be possible. Am I missing something?

**Comment by SeeSharpSoft** [comment]
Guess you have access to ["Database Tools and SQL" plugin](https://www.jetbrains.com/help/idea/editing-csv-and-tsv-files.html). You can access it via the editors context menu entry "Edit as Table".

The CSV plugin versions 2.9.* were not functional in IntelliJ 2020.* Ultimate due to conflicting CSV filetype definitions. This was resolved with v2.10.0, but I am still working on a better integration with the mention database plugin.
