### ISSUE TITLE
CSV and TSV icons are inconsistent (and outdated)

### ISSUE THREAD

**Issue by sabi0** [SeeSharpSoft/intellij-csv-validator#23]
CSV and TSV files icons are not implemented in the same style:
![image](https://user-images.githubusercontent.com/11509875/38809038-7ce62506-4182-11e8-9c24-94c3a74a3f47.png)

Besides they both are poorly readable and do not match IDEA (2018.1) file types icons style:
![image](https://user-images.githubusercontent.com/11509875/38809085-abf85a3a-4182-11e8-8a09-2cfb6ff90f70.png)

**Comment by SeeSharpSoft** [comment]
@sabi0 I didn’t know about the new file type icon style - thanks for pointing this out! But please keep in mind: The plugin supports Jetbrains IDE versions down to 2016.3.2 and will hopefully support newer versions as well. I’d like to keep the CSV/TSV icons stable across all versions. And at the end the icons should be associated with this plugin and not pretend to be a natively supported file type.

Regarding the style: The initial CSV icon was from a free icon library - and its 16px version is indeed poorly readable. That actually was the reason that I intentionally(!) did choose another style for the TSV icon but kept the color, so that the text is not the only differentiation.

Unfortunately I am not a designer and quite a novice with all kinds of graphical tools... Contribution welcome!

**Comment by SeeSharpSoft** [comment]
Icons reworked with #25

**Comment by SeeSharpSoft** [comment]
New icons (handmade):
CSV: ![csv-icon](https://user-images.githubusercontent.com/3205800/39914318-fa18e71c-5504-11e8-9015-d5e12d75a516.png)
TSV: ![tsv-icon](https://user-images.githubusercontent.com/3205800/39914317-f9fdcc02-5504-11e8-8196-aa931a1930e3.png)

Please note: As said before, I'd like to have the icons not in the very same style as Jetbrains IDE 2018.* on purpose - mainly for not to be confused with a "native" supported file format but associated with this plugin, and also being independent of icon style changes across IDE versions.
