### ISSUE TITLE
Indentation settings problem

### ISSUE THREAD

**Issue by egoisticalgoat** [SeeSharpSoft/intellij-csv-validator#6]
I've already discussed [this issue on the PhpStorms issue tracker](https://youtrack.jetbrains.com/issue/WI-39643) before pinpointing the problem to this plugin, so i'll just do a very quick recap.

When setting the Tab Size/Indent to the default (4), PhpStorm will use the default value upon the next restart. But it seems like your plugin changes that default indentation size from 4 to 1, which means that I have to set those settings again on every startup. 

[These lines](https://github.com/SeeSharpSoft/intellij-csv-validator/commit/d7734d3f87d013b77d79fa15541f66f63f65000a#diff-ca488d826fe24d0eeab72e9c24706287R45) seem to be the cause, and i can understand what you wanted to do, but it sadly has the side effect that it also changes those settings for other files, e.g. smarty templates, which i edit on a daily basis.

**Comment by SeeSharpSoft** [comment]
Thx alot for pointing this out - I will investigate ASAP into the issue to find a proper solution.

**Comment by SeeSharpSoft** [comment]
@egoisticalgoat First: I am sorry for you inconvenience!! I just noticed the trouble you went through in finding the root cause of this issue with the JetBrains support. And I am quite impressed about your investigation skills.

I did a bit of investigation myself and tried to understand the settings concept of JetBrains better. By reading some code of other plugins I am certain that I found the correct way to initialize the defaults for language specific settings. I will publish an update of the plugin soonish but it might take up to 3 days until it is in the JetBrains plugin repo. Please feel free to download the [hotfix release](https://github.com/SeeSharpSoft/intellij-csv-validator/releases/tag/1.4.1) - and please let me know if you still encounter this problems.

**Comment by egoisticalgoat** [comment]
Thanks a lot for the quick fix!
I've just updated to 1.4.1 and my problem is gone! 

Hope you had a relaxing weekend, and i wish you a relaxing week then :grin:

**Comment by SeeSharpSoft** [comment]
Thanks - great to hear!
