### ISSUE TITLE
Can't open a TSV file

### ISSUE THREAD

**Issue by chairbender** [SeeSharpSoft/intellij-csv-validator#66]
Suddenly, I am unable to open most TSV files in IntelliJ. I just click the file in the explorer and nothing happens. Disabling this plugin resolves this issue.

I can open some of the files, but not all of them. Doesn't matter if they are small or large. It seems like the files that I can't open might be ones that I had left open when I last exited IntelliJ.

**Comment by SeeSharpSoft** [comment]
Thanks for reporting - I can re-produce the issue and will investigate ASAP!

**Comment by SeeSharpSoft** [comment]
Included in upcoming release 1.9.1 - I will push it to the plugin repo shortly but there is always a short delay (normally 1-2 workdays) due to the plugin approval process.

Until the release is available, you can go with the following workaround:

Right-click the CSV-file and choose 'Mark as plain text'. Then you will be able to open the file. It is also possible set the file-type back to CSV for the session - unfortunately after restarting the IDE you have to do it again.
